
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getUsage(orgId: string, sessionToken: string) : Promise<Result<UsageData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_usage", { orgId, sessionToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Settings> {
    return await TAURI_INVOKE("get_default_settings");
},
/**
 * Save credentials to OS keychain and update in-memory state
 */
async saveCredentials(orgId: string, sessionToken: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_credentials", { orgId, sessionToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if credentials are configured (without exposing them)
 */
async getIsConfigured() : Promise<Result<boolean, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_is_configured") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear credentials from OS keychain and stop auto-refresh
 */
async clearCredentials() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_credentials") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update auto-refresh settings and restart loop
 */
async setAutoRefresh(enabled: boolean, intervalMinutes: number) : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_auto_refresh", { enabled, intervalMinutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trigger immediate refresh
 */
async refreshNow() : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update notification settings in memory (frontend saves to store)
 */
async setNotificationSettings(settings: NotificationSettings) : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notification_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get usage history by time range preset
 */
async getUsageHistoryByRange(range: string) : Promise<Result<UsageHistoryRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_usage_history_by_range", { range }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get usage statistics for a time range
 */
async getUsageStats(range: string) : Promise<Result<UsageStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_usage_stats", { range }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clean up old history data
 */
async cleanupHistory(retentionDays: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_history", { retentionDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Metric statistics
 */
export type MetricStats = { current: number | null; change: number | null; velocity: number | null }
/**
 * Notification rule for a single usage type
 */
export type NotificationRule = { interval_enabled: boolean; interval_percent: number; threshold_enabled: boolean; thresholds: number[]; 
/**
 * Enable time-remaining notifications (notify when close to reset)
 */
time_remaining_enabled: boolean; 
/**
 * Time thresholds in minutes (e.g., [30, 60] = notify at 30min and 1hr before reset)
 */
time_remaining_minutes: number[] }
/**
 * Notification settings for all usage types
 */
export type NotificationSettings = { enabled: boolean; five_hour: NotificationRule; seven_day: NotificationRule; seven_day_sonnet: NotificationRule; seven_day_opus: NotificationRule }
export type Settings = { organization_id: string | null; session_token: string | null; refresh_interval_minutes: number }
export type UsageData = { five_hour: UsagePeriod | null; seven_day: UsagePeriod | null; seven_day_sonnet: UsagePeriod | null; seven_day_opus: UsagePeriod | null }
/**
 * Usage history record matching frontend TypeScript interface
 */
export type UsageHistoryRecord = { id: number; timestamp: string; five_hour_utilization: number | null; five_hour_resets_at: string | null; seven_day_utilization: number | null; seven_day_resets_at: string | null; sonnet_utilization: number | null; sonnet_resets_at: string | null; opus_utilization: number | null; opus_resets_at: string | null }
export type UsagePeriod = { utilization: number; resets_at: string | null }
/**
 * Usage statistics for a time range
 */
export type UsageStats = { fiveHour: MetricStats; sevenDay: MetricStats; sonnet: MetricStats; opus: MetricStats; recordCount: number; periodHours: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
