// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getUsage: (provider: ProviderKind, orgId: string | null, sessionToken: string | null) => typedError<UsageSnapshot, string>(__TAURI_INVOKE("get_usage", { provider, orgId, sessionToken })),
	getDefaultSettings: () => __TAURI_INVOKE<Settings>("get_default_settings"),
	saveCredentials: (orgId: string, sessionToken: string) => typedError<null, string>(__TAURI_INVOKE("save_credentials", { orgId, sessionToken })),
	clearCredentials: () => typedError<null, string>(__TAURI_INVOKE("clear_credentials")),
	getProviderStatuses: () => typedError<ProviderStatus[], null>(__TAURI_INVOKE("get_provider_statuses")),
	setActiveProvider: (provider: ProviderKind) => typedError<null, null>(__TAURI_INVOKE("set_active_provider", { provider })),
	setAutoRefresh: (enabled: boolean, intervalMinutes: number) => typedError<null, null>(__TAURI_INVOKE("set_auto_refresh", { enabled, intervalMinutes })),
	setHourlyRefresh: (enabled: boolean) => typedError<null, null>(__TAURI_INVOKE("set_hourly_refresh", { enabled })),
	refreshNow: () => typedError<null, null>(__TAURI_INVOKE("refresh_now")),
	setNotificationSettings: (settings: NotificationSettings) => typedError<null, null>(__TAURI_INVOKE("set_notification_settings", { settings })),
	getUsageHistoryByRange: (provider: ProviderKind, range: string) => typedError<UsageHistoryPoint[], string>(__TAURI_INVOKE("get_usage_history_by_range", { provider, range })),
	getUsageStats: (provider: ProviderKind, range: string) => typedError<UsageStats, string>(__TAURI_INVOKE("get_usage_stats", { provider, range })),
	cleanupHistory: (retentionDays: number) => typedError<number, string>(__TAURI_INVOKE("cleanup_history", { retentionDays })),
};

/* Types */
export type NotificationRule = {
	interval_enabled: boolean,
	interval_percent: number,
	threshold_enabled: boolean,
	thresholds: number[],
	time_remaining_enabled: boolean,
	time_remaining_minutes: number[],
};

export type NotificationSettings = {
	enabled: boolean,
	rules: { [key in string]: NotificationRule },
};

export type ProviderKind = "claude" | "codex";

export type ProviderStatus = {
	provider: ProviderKind,
	configured: boolean,
	source: string,
	message: string | null,
};

export type Settings = {
	active_provider: ProviderKind,
	refresh_interval_minutes: number,
};

export type UsageHistoryPoint = {
	id: number,
	provider: ProviderKind,
	timestamp: string,
	windowKey: string,
	label: string,
	utilization: number,
	resetsAt: string | null,
};

export type UsageSnapshot = {
	provider: ProviderKind,
	windows: UsageWindow[],
	accountEmail: string | null,
	planType: string | null,
};

export type UsageStats = {
	windows: WindowStats[],
	recordCount: number,
	periodHours: number,
};

export type UsageWindow = {
	key: string,
	label: string,
	utilization: number,
	resetsAt: string | null,
	windowDurationSeconds: number | null,
};

export type WindowStats = {
	key: string,
	label: string,
	current: number | null,
	change: number | null,
	velocity: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

